_assets_model("eff/Crit", "lik_crit")
_assets_model("eff/CritAbility", "lik_crit_ability")
_assets_model("ttg/+", "lik_ttg_+")
_assets_model("ttg/-", "lik_ttg_-")
_assets_model("ttg/0", "lik_ttg_0")
_assets_model("ttg/1", "lik_ttg_1")
_assets_model("ttg/2", "lik_ttg_2")
_assets_model("ttg/3", "lik_ttg_3")
_assets_model("ttg/4", "lik_ttg_4")
_assets_model("ttg/5", "lik_ttg_5")
_assets_model("ttg/6", "lik_ttg_6")
_assets_model("ttg/7", "lik_ttg_7")
_assets_model("ttg/8", "lik_ttg_8")
_assets_model("ttg/9", "lik_ttg_9")
_assets_model("ttg/Crit3", "lik_ttg_crit")
_assets_model("ttg/Avoid", "lik_ttg_avoid")
_assets_model("ttg/CritAbility", "lik_ttg_crit_ability")
_assets_model("ttg/Immune_Damage", "lik_ttg_immuneDamage")
_assets_model("ttg/Immune_Enchant", "lik_ttg_immuneEnchant")
_assets_model("ttg/Immune_Invincible", "lik_ttg_immuneInvincible")
_assets_model("ttg/Punish", "lik_ttg_punish")
_assets_model("ttg/Enchant_dark", "lik_ttg_e_dark")
_assets_model("ttg/Enchant_fire", "lik_ttg_e_fire")
_assets_model("ttg/Enchant_grass", "lik_ttg_e_grass")
_assets_model("ttg/Enchant_ice", "lik_ttg_e_ice")
_assets_model("ttg/Enchant_light", "lik_ttg_e_light")
_assets_model("ttg/Enchant_poison", "lik_ttg_e_poison")
_assets_model("ttg/Enchant_rock", "lik_ttg_e_rock")
_assets_model("ttg/Enchant_thunder", "lik_ttg_e_thunder")
_assets_model("ttg/Enchant_water", "lik_ttg_e_water")
_assets_model("ttg/Enchant_wind", "lik_ttg_e_wind")
_assets_model("ttg/Enchant_steel", "lik_ttg_e_steel")
_assets_model("interface/BossAlert") -- 指示器[条]100*750
_assets_model("interface/BossAlertRing") -- 指示器[圆]160
_assets_model("interface/BossAlertSquare") -- 指示器[正方]160