--- 蝎子
TPL_UNIT.BloodBeetle = UnitTpl("Archnathid")
    :modelAlias("BloodBeetle")
    :icon("unit\\HunterPetSilithid")
    :superposition("noAttack", 1)
    :itemSlot({ TPL_ITEM.IT1, TPL_ITEM.IT2 })
    :iconMap("px", 0.003, 0.003)
    :elite(true)
    :reborn(0.5)
    :hp(1000):hpRegen(50)
    :mp(1000):mpRegen(10)
    :move(0)
    :attackSpaceBase(1)
    :attack(51)
    :attackRange(1000)
    :attackModePush(AttackMode():mode("lightning"):lightningType(LIGHTNING_TYPE.suckBlue):focus(3):damageType(DAMAGE_TYPE.thunder))
    :punish(10000)