TPL_UNIT.Footman = UnitTpl("Footman")
    :superposition("noAttack", 1)
    :reborn(3)
    :hp(300)
    :mp(100)
    :mpRegen(5)
    :move(0)

TPL_UNIT.MortarTeam = UnitTpl("MortarTeam")
    :hp(100)
    :attackMode(AttackMode():missileModel("MortarMissile"):height(500):speed(300))
    :attack(3)
    :attackRange(300)
    :attackSpaceBase(0.3)
    :move(100)

TPL_UNIT.Rifleman = UnitTpl("Rifleman")
    :hp(100)
    :attackMode(AttackMode():missileModel("FireBallMissile"):height(0):speed(350))
    :attack(3)
    :attackRange(300)
    :attackSpaceBase(0.3)
    :move(100)

TPL_UNIT.BloodElfDragonHawk = UnitTpl("BloodElfDragonHawk")
    :hp(100)
    :attackMode(AttackMode():missileModel("DragonHawkMissile"):height(0):speed(200))
    :attack(3)
    :attackRange(300)
    :attackSpaceBase(0.3)
    :move(100)

TPL_UNIT.WyvernRider = UnitTpl("WyvernRider")
    :hp(100)
    :attackMode(AttackMode():missileModel("GryphonRiderMissile"):height(0):speed(400))
    :attack(3)
    :attackRange(300)
    :attackSpaceBase(0.3)
    :flyHeight(200)
    :move(100)

TPL_UNIT.ChaosWarlockGreen = UnitTpl("Shaman")
    :modelAlias("ChaosWarlockGreen")
    :hp(100)
    :attack(3)
    :attackMode(AttackMode():lightningType(LIGHTNING_TYPE.thunderRed))
    :attackRange(300)
    :attackSpaceBase(0.3)
    :move(100)