TPL_UNIT.Footman = UnitTpl("Footman")
    :modelAlias("Footman")
    :icon("unit\\Footman")
    :superposition("noAttack", 1)
    :itemSlot({ TPL_ITEM.IT1, TPL_ITEM.IT2 })
    :iconMap("px", 0.003, 0.003)
    :elite(true)
    :reborn(0.5)
    :hp(1000):hpRegen(50)
    :mp(1000):mpRegen(10)
    :move(522)
    :attackSpaceBase(0.7)
    :attack(77)
    :attackRange(1000)
    :attackMode(AttackMode():mode("lightning"):lightningType(LIGHTNING_TYPE.suckBlue):focus(3):damageType(DAMAGE_TYPE.thunder))
    :punish(10000)